### ISSUE TITLE
Update data model with additional Program properties

### ISSUE THREAD

**Issue by PhilipMusk** [CBIIT/icdc-model-tool#1]
Need to update data model with additional Program properties.
 
Specifically, need to add properties for curated, i.e. non-derived, program-centric metadata as follows:

- Program description - a short (2-3 sentence) descriptive text that outlines the nature of any given Program

- External program URL - an outward pointing URL for the web page that's deemed to be the single most informative starting point for someone wanting to learn more about any given Program

**Comment by majensen** [comment]
closed @ 4a8242c /
