### ISSUE TITLE
Update data model with additional Program properties

### ISSUE THREAD

**Issue by PhilipMusk** [CBIIT/icdc-model-tool#11]
Need to add a couple more Program properties in order to more fully support front end rendering of program views.

Specifically:
program_acronym
program_short_description - of questionable value
program_sort_order - also of questionable value

**Comment by majensen** [comment]
Closed at https://github.com/CBIIT/icdc-model-tool/commit/a25a9b52436cf0a640cf8873e6196a44a1056816
and merged to master (pr #12)
