### ISSUE TITLE
Update data model with additional Study properties.

### ISSUE THREAD

**Issue by PhilipMusk** [CBIIT/icdc-model-tool#2]
Need to update data model with additional Study properties.
 
Specifically, need to add properties for curated, i.e. non-derived, study-centric metadata as follows:

- Study description - a relatively short (5-6 sentence) descriptive text that outlines the nature of any given Study. For a Study that's identified as a clinical trial by the proposed "study type" property (see below), this text would be culled directly from the study protocol's precis or summary section

- Study type - a 2-3 word classification of any given study as a "clinical trial", or a "transcriptomics and proteomics analysis", etc., with the verbiage used assigned on a case by case basis

- Conducted when - a date range indicating the time period over which the study was conducted

**Comment by majensen** [comment]
closed @ 164401c
