### ISSUE TITLE
Update data model with additional Diagnosis properties

### ISSUE THREAD

**Issue by PhilipMusk** [CBIIT/icdc-model-tool#3]
Need to update data model with additional Diagnosis properties relevant to NCATS-derived data

Specifically, need to add the following properties:

- concurrent_disease

- concurrent_disease_type

- immunophenotype - of questionable value; within the NCATS data, this field is used to delineate B cell vs. T cell lymphoma. We could so easily concatenate the values in this field with those in the NCATS "tumor_type_specific" field to produce a very specific value for ICDC's "disease_term", and thereby avoid adding this property, yet make use of its data.

**Comment by majensen** [comment]
closed @ 7738f9e
