### ISSUE TITLE
Update data model with additional Sample properties

### ISSUE THREAD

**Issue by PhilipMusk** [CBIIT/icdc-model-tool#4]
Need to update data model with additional Sample properties relevant to NCATS-derived data.

Specifically, need to add properties for pathology annotations specific to tumor samples:

- sample_id

- sample_type (to indicate tissue vs. blood vs. urine, etc.)

- general_sample_pathology (to indicate normal vs. tumor sample)

- date_of_sample_collection

- necropsy_sample

- length_of_tumor (the length of the tumor from which the tumor sample was taken)

- width_of_tumor (the width of the tumor from which the tumor sample was taken)

- analysis_area

analysis_area_percentage_tumor
analysis_area_percentage_stroma
analysis_area_percentage_glass
analysis_area_percenatge_pigmented_tumor
total_tissue_area
tumor_tissue_area
non_tumor_tissue_area

- percentage_tumor

- percentage_stroma

- comment

Some of these fields (especially those not bulleted above) are so NCATS-specific that I question the value of us accommodating them and their data. But on the other hand, Greg included the fields and their values, so he sees this as useful data.

**Comment by majensen** [comment]
Closed @ dd5893d
