### ISSUE TITLE
Assorted model updates required

### ISSUE THREAD

**Issue by PhilipMusk** [CBIIT/icdc-model-tool#42]
Assorted model updates are required in order to support upload on minimum viable content for MVP release:
Need a relationship from File directly to Study, for study-level data files
Need a relationship from Visit to Case, for situations where a Visit can't be unambiguously mapped to a Cycle
Need a relationship from Adverse Event to Case, to replace the relationship from Adverse Event to Visit - AEs are based on date of onset, not visit
Advocate proactively adding sample_site and specific_sample_pathology properties to Sample
Need to add "not applicable" as an acceptable term for general_sample_pathology to accommodate blood samples
Need to remove the s from the file_locations property
Need to change cohort_dose property to type = string to facilitate upload of inconsistent data

**Comment by majensen** [comment]
<img width="872" alt="image" src="https://user-images.githubusercontent.com/82073/67335867-6416f580-f4f2-11e9-8239-fc0f1ec58010.png">

**Comment by majensen** [comment]
I should show you how to validate on your machine --
