### ISSUE TITLE
How to generate SVG

### ISSUE THREAD

**Issue by fvitas** [CBIIT/icdc-model-tool#46]
Hi, I'm playing a bit with a tool and I wanted to generate svg.
I run `bin/model-tool -g image.svg icdc-model.yml icdc-model-props.yml`, but I didn't get any svg output. Yamls are from this repo.

Can you tell me what am I missing?

**Comment by majensen** [comment]
Hmm - can you send your command line and whatever output you got?

**Comment by fvitas** [comment]
Sorry I didn't provide more data. 
It's working now, so I will close this.

For other people that may run into this, I'm running on macos Catalina 10.15.2.
I found out that GraphViz2 was not installed correctly because of some error 'EXTERN.h' file not found.

So I had to update perl
`brew install perl`
`brew link perl`

and I run this again
`perl Build.PL`
`./Build`
`./Build installdeps  --cpan_client "cpanm"`
`./Build install`

and it works

**Comment by majensen** [comment]
Thanks @fvitas -- we did some refactoring and the install/run docs fell into the bit bucket. I added these back- Please have a look at https://github.com/CBIIT/bento-mdf, where the tools live, and the doc at https://github.com/CBIIT/bento-mdf/tree/master/drivers/Perl/make-model
Appreciate your interest!
