### ISSUE TITLE
Update data model with additional Demographic properties

### ISSUE THREAD

**Issue by PhilipMusk** [CBIIT/icdc-model-tool#5]
Need to update data model with additional Demographic properties relevant to NCATS-derived data.

Specifically, need to add the following properties:

- weight - to indicate the subject's weight at the time the subject was enrolled and biospecimens were acquired, at least in the case of studies that are not longitudinal in nature

- neutered_indicator - a Boolean indicator as to whether the subject is spayed or neutered. Not needed thus far, because at least for the COTC007B study, the data in C3D captures whether the subject has been spayed/neutered as part of whether the subject in female/male. Whereas the NCATS data captures sex and spayed/neutered status as separate data elements.

**Comment by majensen** [comment]
closed @ 8f94b6f
